# Generated by Django 5.2.7 on 2025-11-08 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Recycling)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly name (auto-generated)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('icon', models.CharField(default='🌱', help_text='Emoji icon for this category', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Catchy title for your tip', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('content', models.TextField(help_text='Detailed explanation of your tip')),
                ('image', models.ImageField(blank=True, help_text='Optional image to illustrate your tip', null=True, upload_to='tips/')),
                ('is_published', models.BooleanField(default=True, help_text='Is this tip visible to everyone?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who created this tip', on_delete=django.db.models.deletion.CASCADE, related_name='tips', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Category this tip belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tips', to='tips.category')),
            ],
            options={
                'verbose_name': 'Tip',
                'verbose_name_plural': 'Tips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who liked the tip', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('tip', models.ForeignKey(help_text='The tip that was liked', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tips.tip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Your comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who wrote this comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('tip', models.ForeignKey(help_text='The tip being commented on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tips.tip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['-created_at'], name='tips_tip_created_d817e7_idx'),
        ),
        migrations.AddIndex(
            model_name='tip',
            index=models.Index(fields=['slug'], name='tips_tip_slug_90cd7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'tip')},
        ),
    ]
