# Generated by Django 5.2.6 on 2025-11-24 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this category was approved', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Moderator/Admin who approved this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this category is approved for use'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
