# Generated by Django 5.2.7 on 2025-11-04 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself', max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='eco_interests',
            field=models.CharField(blank=True, help_text='Your eco-friendly interests (e.g., recycling, energy saving)', max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='followers_count',
            field=models.IntegerField(default=0, help_text='Number of followers'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='following_count',
            field=models.IntegerField(default=0, help_text='Number of people following'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='impact_score',
            field=models.IntegerField(default=0, help_text='Environmental impact score'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified eco-contributor'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, help_text='Where are you from?', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tips_count',
            field=models.IntegerField(default=0, help_text='Number of tips shared'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, help_text='Your personal website or blog'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('contributor', 'Contributor'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
