# Generated by Django 5.2.7 on 2025-11-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_education_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='following_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='impact_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tips_count',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('moderator', 'Moderator'), ('admin', 'Administrator')], default='user', max_length=20),
        ),
    ]
