# Generated by Django 5.2.7 on 2025-11-24 21:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Session key for anonymous users', max_length=40, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of activity')),
                ('visits_count', models.PositiveIntegerField(default=0, help_text='Number of visits on this date')),
                ('page_views', models.PositiveIntegerField(default=0, help_text='Number of pages viewed')),
                ('tips_viewed', models.JSONField(blank=True, default=list, help_text='List of tip IDs viewed')),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='Time spent in seconds')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User (null for anonymous users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-date', '-last_activity'],
                'indexes': [models.Index(fields=['user', 'date'], name='accounts_us_user_id_af1719_idx'), models.Index(fields=['session_key', 'date'], name='accounts_us_session_0888cb_idx')],
            },
        ),
    ]
