# Generated by Django 5.2.6 on 2025-11-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followers_count',
            field=models.IntegerField(default=0, help_text='Number of followers'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='following_count',
            field=models.IntegerField(default=0, help_text='Number of people following'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='impact_score',
            field=models.IntegerField(default=0, help_text='Environmental impact score'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tips_count',
            field=models.IntegerField(default=0, help_text='Number of tips shared'),
        ),
    ]
